
'use strict'
const swaggerJsdoc = require('swagger-jsdoc');

const swaggerOptions = {
    swaggerDefinition: {
        info: {
            version: "1.0.0",
            title: "Scrummers API",
            description: "Scrummers API Information",
            contact: {
                name: "Alejandro Martinez"
            },
            servers: ["http://localhost:8080"]
        }
    },
    // ['.routes/*.js']
    apis: ["./app/controller/*.js"]
};

/*const options = {  
    // List of files to be processed.
    apis: ['./app/controller/*.js'],
      // You can also set globs for your apis
    // e.g. './routes/*.js'
    basePath: '/',  
    swaggerDefinition: {    
        info: {      
            description: 'Test API with autogenerated swagger doc',      
            swagger: '2.0',      
            title: 'Scrummers API',      
            version: '1.0.0',    
        },  
    },
};
const specs = swaggerJsdoc(options);

//export default specs;
//module.exports.specs;
exports.specs;*/